# Generated by Django 5.2.4 on 2025-08-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts_media/', verbose_name='Média'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10, null=True, verbose_name='Type de média'),
        ),
    ]
