# Generated by Django 5.2.4 on 2025-10-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_post_image_remove_post_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.AddField(
            model_name="post",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL Vidéo"),
        ),
    ]
