# Generated by Django 5.2.4 on 2025-08-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_post_image_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
